# Generated by Django 3.1.7 on 2021-04-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Nazwa wycieczki')),
                ('description1', models.CharField(max_length=1000, verbose_name='Opis1 wycieczki')),
                ('description2', models.CharField(blank=True, max_length=1000, verbose_name='Opis2 wycieczki')),
                ('description3', models.CharField(blank=True, max_length=1000, verbose_name='Opis3 wycieczki')),
                ('description4', models.CharField(blank=True, max_length=1000, verbose_name='Opis4 wycieczki')),
                ('country', models.CharField(max_length=50, verbose_name='Kraj wycieczki')),
                ('currency', models.CharField(max_length=5, verbose_name='Skrót waluty')),
                ('timezone', models.CharField(max_length=7, verbose_name='Strefa czasowa')),
                ('stars', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='Gwiazdki hotelu wycieczki')),
                ('temperature', models.CharField(choices=[('Niska', 'Niska'), ('Średnia', 'Średnia'), ('Wysoka', 'Wysoka')], max_length=15, verbose_name='Temperatura')),
                ('climate', models.CharField(choices=[('Górski', 'Górski'), ('Morski', 'Morski'), ('Kontynentalny', 'Kontynentalny'), ('Śródziemnomorski', 'Śródziemnomorski'), ('Monsunowy', 'Monsunowy'), ('Stepowy', 'Stepowy'), ('Pustynny', 'Pustynny')], max_length=20, verbose_name='Klimat')),
                ('landscape', models.CharField(choices=[('Góry', 'Góry'), ('Plaża', 'Plaża'), ('Pustynia', 'Pustynia'), ('Las', 'Las'), ('Miasto', 'Miasto'), ('Wieś', 'Wieś'), ('Morze', 'Morze')], max_length=15, verbose_name='Krajobraz')),
                ('type', models.CharField(choices=[('Aktywny wypoczynek', 'Aktywny wypoczynek'), ('Wypoczynek', 'Wypoczynek'), ('Zwiedzanie', 'Zwiedzanie')], max_length=20, verbose_name='Rodzaj wycieczki')),
                ('transport', models.CharField(choices=[('Samolot', 'Samolot'), ('Dojazd Własny', 'Dojazd Własny'), ('Autobus', 'Autobus')], max_length=20, verbose_name='Rodzaj transportu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena wycieczki')),
                ('duration', models.IntegerField(verbose_name='Ilość dni wycieczki')),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.trip')),
            ],
        ),
    ]
