# Generated by Django 3.1.7 on 2021-04-29 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='User ID')),
                ('persons', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ilość osób')),
                ('phone', models.CharField(max_length=12, verbose_name='Numer kontaktowy')),
                ('guide', models.BooleanField(default=0, verbose_name='Prywatny przewodnik')),
                ('room', models.BooleanField(default=0, verbose_name='Pokój premium')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Cena wycieczki')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.trip')),
            ],
        ),
    ]
