# Generated by Django 3.1.7 on 2021-05-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20210505_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='temperature',
        ),
    ]
