# Generated by Django 3.1.7 on 2021-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20210505_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='countryEN',
            field=models.CharField(default='Italy', max_length=50, verbose_name='Kraj wycieczki po angielsku'),
            preserve_default=False,
        ),
    ]
