# Generated by Django 3.1.7 on 2021-05-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_trip_countryen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='stars',
            new_name='hotelstars',
        ),
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2, verbose_name='Ocena wycieczki'),
            preserve_default=False,
        ),
    ]
