# Generated by Django 3.1.7 on 2021-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20210505_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(default='brak', max_length=50, verbose_name='Miasto wycieczki'),
            preserve_default=False,
        ),
    ]
