# Generated by Django 3.1.7 on 2021-05-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_trip_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description4',
        ),
        migrations.AddField(
            model_name='trip',
            name='all_inclusive_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Opis all inclusive'),
        ),
        migrations.AddField(
            model_name='trip',
            name='beach_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Opis Plaży'),
        ),
        migrations.AddField(
            model_name='trip',
            name='benefits_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Swiadczenia'),
        ),
        migrations.AddField(
            model_name='trip',
            name='for_free_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Gratisy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='head_description',
            field=models.CharField(default='default', max_length=1000, verbose_name='Główny opis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_decription',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Opis Hotelu'),
        ),
        migrations.AddField(
            model_name='trip',
            name='room_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Opis pokoju'),
        ),
        migrations.AddField(
            model_name='trip',
            name='sport_and_entertainment_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Sport i rozrywka'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_plan_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Plan wycieczki'),
        ),
    ]
