# Generated by Django 3.1.7 on 2021-05-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_auto_20210505_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Opis miejsca'),
        ),
    ]
