# Generated by Django 3.1.7 on 2021-05-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_auto_20210505_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='hotel_decription',
            new_name='hotel_description',
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotelstars',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='Gwiazdki hotelu'),
        ),
    ]
