# Generated by Django 3.1.7 on 2021-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_auto_20210505_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippicture',
            name='picture',
            field=models.ImageField(upload_to='travels/'),
        ),
    ]
