# Generated by Django 3.1.7 on 2021-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0013_auto_20210506_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippicture',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
