# Generated by Django 3.1.7 on 2021-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0015_auto_20210506_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_plan_description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Plan wycieczki'),
        ),
    ]
