# Generated by Django 3.1.7 on 2021-05-06 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0016_auto_20210506_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Miejsce wycieczki'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Cena wycieczki dla 1os.'),
        ),
        migrations.AlterField(
            model_name='tripdates',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Data zakończenia'),
        ),
    ]
