# Generated by Django 3.1.7 on 2021-05-16 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0020_auto_20210511_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_place', models.CharField(choices=[('Tylko po Polsce', 'Samolot'), ('Po Polsce oraz za granicą', 'Dojazd Własny'), ('Autobus', 'Tylko za granicą')], max_length=50, verbose_name='Jakie podróże Pana/Panią interesują?')),
                ('preferred_transport', models.CharField(choices=[('Samolot', 'Samolot'), ('Dojazd Własny', 'Dojazd Własny'), ('Autobus', 'Autobus')], max_length=50, verbose_name='Jaki środek transportu Pan/Pani preferuje?')),
                ('preferred_type', models.CharField(choices=[('Aktywny wypoczynek', 'Aktywny wypoczynek'), ('Wypoczynek', 'Wypoczynek'), ('Zwiedzanie', 'Zwiedzanie')], max_length=50, verbose_name='Jaki cel wycieczki wybrałby/wybrałaby Pan/Pani za najbardziej odpowiedni dla siebie?')),
                ('preferred_landscape', models.CharField(choices=[('Góry', 'Góry'), ('Plaża', 'Plaża'), ('Pustynia', 'Pustynia'), ('Las', 'Las'), ('Miasto', 'Miasto'), ('Wieś', 'Wieś'), ('Morze', 'Morze')], max_length=50, verbose_name='Jaki krajobraz wybrałby/wybrałaby Pan/Pani za najbardziej odpowiedni dla siebie?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
