# Generated by Django 3.1.7 on 2021-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0021_polling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='preferred_place',
            field=models.CharField(choices=[('Tylko po Polsce', 'Tylko po Polsce'), ('Po Polsce oraz za granicą', 'Po Polsce oraz za granicą'), ('Tylko za granicą', 'Tylko za granicą')], max_length=50, verbose_name='Jakie podróże Pana/Panią interesują?'),
        ),
    ]
